# numpy引入

In [1]:
import torch
import numpy as np
a = np.array([2,3.3])
print(torch.from_numpy(a))
a = np.ones([2,3])
print(torch.from_numpy(a))

tensor([2.0000, 3.3000], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


# 大小写的tensor
- 大写的给shape，小写的给数值

In [2]:
print(torch.tensor([2.,3.2]))
print(torch.Tensor(2,3))

tensor([2.0000, 3.2000])
tensor([[-5.5906e+06,  4.5863e-41, -5.5906e+06],
        [ 4.5863e-41,  4.4842e-44,  0.0000e+00]])


# 生成未初始化的数据

In [4]:
print(torch.empty(2,3))
print(torch.FloatTensor(1,2,2))

tensor([[0.0000e+00, 0.0000e+00, 1.2106e-33],
        [0.0000e+00, 1.4013e-45, 0.0000e+00]])
tensor([[[1.0431e-33, 0.0000e+00],
         [1.0435e-33, 0.0000e+00]]])


> 未初始化的数据会造成生成非常大/小的数字
> 一定要进行覆盖

# 随机初始化

In [5]:
# [0,1]之间采样
print(torch.rand(3,3))
# 自定义采样空间[a,b)
print(torch.randint(1, 10, [3,3]))

tensor([[0.6636, 0.9107, 0.9760],
        [0.3689, 0.6611, 0.1208],
        [0.2848, 0.3128, 0.7600]])
tensor([[5, 1, 2],
        [6, 1, 8],
        [6, 2, 5]])


# 正态分布初始化

In [6]:
print(torch.randn(3,3))

tensor([[-1.0896,  0.1753, -0.4359],
        [-1.0214,  0.5174, -1.2513],
        [ 0.4487,  0.0259, -1.2773]])


# 生成相同的初始化

In [8]:
print(torch.full([2,3],7))
print(torch.full([],7)) # 生成标量
print(torch.full([1],7)) # 成成一维的向量

tensor([[7, 7, 7],
        [7, 7, 7]])
tensor(7)
tensor([7])


# 等差数列

In [9]:
print(torch.arange(0,10))
print(torch.arange(0,10,2))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


# linspace/logspace

In [ ]:
# [0,10]
print(torch.linspace(0,10,steps = 4))
print(torch.linspace(0,10,steps = 11))
# [10^0, 10^-1]
print(torch.linspace(0,-1,steps = 10))

# ones/zeros/eyes

In [10]:
print(torch.ones(3,3))
print(torch.zeros(3,3))
# 最简矩阵
print(torch.eye(3,4))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])


In [12]:
# 生成同shape的矩阵
a = torch.zeros(3,3)
print(torch.ones_like(a))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


# 随机打散

In [13]:
a = torch.rand(2,3)
b = torch.rand(2,2)
# 索引
idx = torch.randperm(2)
print(idx)
print(a[idx])
print(b[idx])
print(a,b)

tensor([0, 1])
tensor([[0.0205, 0.9808, 0.5639],
        [0.5537, 0.3413, 0.2411]])
tensor([[0.7985, 0.0416],
        [0.6324, 0.7053]])
tensor([[0.0205, 0.9808, 0.5639],
        [0.5537, 0.3413, 0.2411]]) tensor([[0.7985, 0.0416],
        [0.6324, 0.7053]])
