# 梯度下降手写数字识别
- 灰度图片表示：一个矩阵打平成一个向量——每一个值0～1之间，表示像素
- 怎样将特征和标签的数据进行拟合：3次矩阵乘法（3次线性模型的叠加）
$$
 pred = W_3 * \{W_2[W_1X + b_1] + b_2\} + b_3
$$
- 数字的label编码存在大小关系，不合适
## onehot编码
- 编码：[0,1,0,0,0] [0,0,0,3,0] 预测：[0.1,0.8,0.1,0,0]
- 损失函数——欧式距离（向量相减再平方）
$$
loss = (pred - y)^2
$$ 
## 非线性部分添加
- ReLU函数：输入的和小于零忽略，大于零输出和
$$
H_1 = relu(XW_1 + b_1)
H_2 = relu(XW_2 + b_1)
H_3 = relu(XW_3 + b_1)
$$
## argmax函数
- 输出概率最大的酯的索引号 
## Tensor
- Int——IntTensor of size()
- float——FloatTensor of size()
- Int array——IntTensor of size[d1,d2,...]
- 数据在CPU上和GPU上是不一样的
## String
- One-hot: dog——[1,0]    cat——[0,1]
- Embedding: Word2vec, glove

In [1]:
import torch
a = torch.randn(2,3)
print(a)
print(a.type()) # 返回数据的类型
print(type(a)) # 返回基本的类型
print(isinstance(a, torch.FloatType)) # 进行检验
print(a.size(0))
print(a.size(1))

tensor([[-0.5280, -1.4632,  1.2567],
        [-2.2470, -0.7795, -0.3811]])
torch.FloatTensor
<class 'torch.Tensor'>
False
2
3


In [4]:
# 数据在CPU/GPU
print(isinstance(a, torch.cuda.FloatTensor))
# 将数据搬运到GPU上
a = a.cuda()
print(isinstance(a, torch.cuda.FloatTensor))

False
True


In [7]:
# 对于标量的生成
print(torch.tensor(1.))
print(torch.tensor(1.3))
# 数据结构
print(torch.tensor(1.3).shape)
print(len(torch.tensor(1.3).shape))
print(torch.tensor(1.3).size())

tensor(1.)
tensor(1.3000)
torch.Size([])
0
torch.Size([])


In [8]:
# 一维张量
print(torch.tensor([1.1,2.2]))
print(torch.FloatTensor(2)) # 随机生成
import numpy as np
data = np.ones(2)
print(torch.from_numpy(data))

tensor([1.1000, 2.2000])
tensor([3.7145e-34, 0.0000e+00])
tensor([1., 1.], dtype=torch.float64)


In [9]:
# 高维张量
print(torch.rand(2,2,2))
print(list(torch.rand(2,2,2).shape))

tensor([[[0.2653, 0.1974],
         [0.3195, 0.4636]],

        [[0.3302, 0.8303],
         [0.2216, 0.3636]]])
[2, 2, 2]


In [ ]:
# 图片数据
fig = torch.rand(2,3,28,28) # 两张照片，颜色，高，宽
print(fig)
print(fig.dim())